# Generated by Codex on 2026-06-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_institution_alter_user_managers_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='accounts.institution'),
        ),
    ]
