# Generated by Codex on 2026-06-13

from django.db import migrations


DEFAULT_INSTITUTION_CODE = 'DEFAULT-ZM'


def assign_default_institution(apps, schema_editor):
    Institution = apps.get_model('accounts', 'Institution')
    AcademicYear = apps.get_model('students', 'AcademicYear')

    institution = Institution.objects.get(code=DEFAULT_INSTITUTION_CODE)
    AcademicYear.objects.filter(institution__isnull=True).update(institution=institution)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_backfill_default_institution'),
        ('students', '0002_academicyear_institution'),
    ]

    operations = [
        migrations.RunPython(assign_default_institution, noop_reverse),
    ]
