# Generated by Codex on 2026-06-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('institution_type', models.CharField(choices=[('university', 'University'), ('college', 'College'), ('secondary_school', 'Secondary School'), ('primary_school', 'Primary School'), ('training_center', 'Training Center'), ('other', 'Other')], default='secondary_school', max_length=30)),
                ('country', models.CharField(default='Zambia', max_length=100)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_institution',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[],
        ),
        migrations.CreateModel(
            name='InstitutionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('administrator', 'Administrator'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent/Guardian'), ('accountant', 'Accountant'), ('viewer', 'Viewer')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_institution_memberships', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_institution_membership',
                'unique_together': {('institution', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='institutionmembership',
            index=models.Index(fields=['institution', 'role', 'is_active'], name='accounts_in_institu_beb8f6_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionmembership',
            index=models.Index(fields=['user', 'is_active'], name='accounts_in_user_id_56aefe_idx'),
        ),
    ]
