# Generated by Codex on 2026-06-13

from django.db import migrations


DEFAULT_INSTITUTION_CODE = 'DEFAULT-ZM'


def infer_membership_role(user_type):
    mapping = {
        'super_admin': 'owner',
        'administrator': 'administrator',
        'teacher': 'teacher',
        'student': 'student',
        'parent': 'parent',
        'accountant': 'accountant',
    }
    return mapping.get(user_type, 'viewer')


def create_default_institution_and_memberships(apps, schema_editor):
    Institution = apps.get_model('accounts', 'Institution')
    InstitutionMembership = apps.get_model('accounts', 'InstitutionMembership')
    User = apps.get_model('accounts', 'User')

    institution, _ = Institution.objects.get_or_create(
        code=DEFAULT_INSTITUTION_CODE,
        defaults={
            'name': 'Default Institution',
            'institution_type': 'secondary_school',
            'country': 'Zambia',
            'is_active': True,
        },
    )

    for user in User.objects.all():
        InstitutionMembership.objects.get_or_create(
            institution=institution,
            user=user,
            defaults={
                'role': infer_membership_role(user.user_type),
                'is_active': True,
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_institution_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_institution_and_memberships, noop_reverse),
    ]
