# Generated by Django 5.2.5 on 2026-06-16 12:48

import accounts.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_user_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_key', models.CharField(choices=[('student_success', 'Student Success Agent'), ('assessment', 'Assessment Agent'), ('learning_coach', 'Learning Coach Agent'), ('research', 'Research Agent'), ('career_guidance', 'Career Guidance Agent'), ('academic_integrity', 'Academic Integrity Agent'), ('content_management', 'Content Management Agent'), ('administrative', 'Administrative Agent'), ('zambian_curriculum', 'Zambian Curriculum Agent'), ('scholarship_opportunities', 'Scholarship & Opportunities Agent')], default='learning_coach', max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='accounts.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adom_institute_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], max_length=20)),
                ('content', models.TextField()),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='adom_institute.aiconversation')),
            ],
            options={
                'db_table': 'adom_institute_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('course_material', 'Teacher-approved notes, slides, videos, and handouts.'), ('policy', 'Institution policies, fee rules, conduct rules, and administrative guides.'), ('past_paper', 'ECZ, college, and university past papers with marking schemes.'), ('curriculum', 'Syllabi, curriculum documents, outcomes, and lesson plans.'), ('research_paper', 'Academic research documents uploaded by staff or library teams.')], max_length=50)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('grade_level', models.CharField(blank=True, max_length=50)),
                ('access_scope', models.CharField(default='institution', max_length=100)),
                ('file', models.FileField(upload_to='knowledge/', validators=[accounts.validators.validate_safe_filename, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv']), accounts.validators.FileSizeValidator(20971520)])),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('ocr', 'OCR'), ('indexing', 'Indexing'), ('ready', 'Ready'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to='accounts.institution')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_knowledge_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adom_institute_knowledge_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('embedding_model', models.CharField(blank=True, max_length=100)),
                ('embedding_vector', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='adom_institute.knowledgedocument')),
            ],
            options={
                'db_table': 'adom_institute_knowledge_chunk',
                'ordering': ['document_id', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_key', models.CharField(choices=[('student_success', 'Student Success Agent'), ('assessment', 'Assessment Agent'), ('learning_coach', 'Learning Coach Agent'), ('research', 'Research Agent'), ('career_guidance', 'Career Guidance Agent'), ('academic_integrity', 'Academic Integrity Agent'), ('content_management', 'Content Management Agent'), ('administrative', 'Administrative Agent'), ('zambian_curriculum', 'Zambian Curriculum Agent'), ('scholarship_opportunities', 'Scholarship & Opportunities Agent')], max_length=80)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('waiting_approval', 'Waiting Approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=30)),
                ('model_profile', models.CharField(default='chat', max_length=50)),
                ('input_payload', models.JSONField(default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('requires_human_approval', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_agent_tasks', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_agent_tasks', to='accounts.institution')),
            ],
            options={
                'db_table': 'adom_institute_agent_task',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['institution', 'agent_key', 'status'], name='adom_institute_task_agent_idx'), models.Index(fields=['created_by', 'created_at'], name='adom_institute_task_user_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('granted', 'Granted'), ('revoked', 'Revoked')], default='granted', max_length=20)),
                ('allow_personalization', models.BooleanField(default=True)),
                ('allow_academic_analysis', models.BooleanField(default=True)),
                ('allow_opportunity_matching', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('policy_version', models.CharField(default='2026-06', max_length=50)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_consents', to='accounts.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adom_institute_consent',
                'indexes': [models.Index(fields=['user', 'status'], name='adom_consent_user_idx'), models.Index(fields=['institution', 'status'], name='adom_consent_inst_idx')],
                'unique_together': {('user', 'institution', 'policy_version')},
            },
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['institution', 'agent_key', 'updated_at'], name='adom_institute_conv_agent_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['user', 'updated_at'], name='adom_institute_conv_user_idx'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['conversation', 'created_at'], name='adom_institute_msg_conv_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['institution', 'source_type'], name='adom_institute_doc_source_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['institution', 'processing_status'], name='adom_institute_doc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['document', 'chunk_index'], name='adom_institute_chunk_doc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgechunk',
            unique_together={('document', 'chunk_index')},
        ),
    ]
