# Generated by Django 5.2.5 on 2026-06-16 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_profile_picture'),
        ('adom_institute', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='ollama', max_length=80)),
                ('model_name', models.CharField(max_length=120)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_entries', to='adom_institute.agenttask')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_entries', to='adom_institute.aiconversation')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_entries', to='accounts.institution')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adom_institute_usage_ledger',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['institution', 'created_at'], name='adom_institute_usage_inst_idx'), models.Index(fields=['user', 'created_at'], name='adom_institute_usage_user_idx'), models.Index(fields=['provider', 'model_name'], name='adom_institute_usage_model_idx')],
            },
        ),
    ]
