# Generated by Django 4.2.7 on 2026-09-30 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_academiccalendar_time_calendar_type_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name']},
        ),
    ]
