# Generated by Django 5.2.5 on 2025-09-01 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='students.class'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teachers.subject'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='exam',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='students.academicyear'),
        ),
        migrations.AddField(
            model_name='exam',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='students.class'),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='academics.exam'),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='teachers.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.examtype'),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_submissions', to='academics.assignment'),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_assignments', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_assignments', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentexamresult',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_results', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='studentexamresult',
            name='exam_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='academics.examsubject'),
        ),
        migrations.AddField(
            model_name='studentexamresult',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.grade'),
        ),
        migrations.AddField(
            model_name='studentexamresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='examsubject',
            unique_together={('exam', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('name', 'academic_year', 'class_obj')},
        ),
        migrations.AlterUniqueTogether(
            name='studentassignment',
            unique_together={('student', 'assignment')},
        ),
        migrations.AlterUniqueTogether(
            name='studentexamresult',
            unique_together={('student', 'exam_subject')},
        ),
    ]
