# Generated by Codex on 2026-06-13

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignments/', validators=[accounts.validators.validate_safe_filename, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv']), accounts.validators.FileSizeValidator(20971520)]),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='submission_file',
            field=models.FileField(upload_to='assignment_submissions/', validators=[accounts.validators.validate_safe_filename, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv']), accounts.validators.FileSizeValidator(20971520)]),
        ),
    ]
