# Generated by Codex on 2026-06-13

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='leave_documents/', validators=[accounts.validators.validate_safe_filename, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv']), accounts.validators.FileSizeValidator(20971520)]),
        ),
    ]
